channels:
- conda-forge
dependencies:
- python=3.11.3
- pip<=24.0
- pip:
  - mlflow==2.12.2
  - cloudpickle==3.0.0
  - numpy==1.24.3
  - packaging==23.1
  - psutil==5.9.5
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.11.4
name: mlflow-env
